INSERT INTO paises (iso, nombre) VALUES('AF', 'Afganistán');
INSERT INTO paises (iso, nombre) VALUES('AX', 'Islas Gland');
INSERT INTO paises (iso, nombre) VALUES('AL', 'Albania');
INSERT INTO paises (iso, nombre) VALUES('DE', 'Alemania');
INSERT INTO paises (iso, nombre) VALUES('AD', 'Andorra');
INSERT INTO paises (iso, nombre) VALUES('AO', 'Angola');
INSERT INTO paises (iso, nombre) VALUES('AI', 'Anguilla');
INSERT INTO paises (iso, nombre) VALUES('AQ', 'Antártida');
INSERT INTO paises (iso, nombre) VALUES('AG', 'Antigua y Barbuda');
INSERT INTO paises (iso, nombre) VALUES('AN', 'Antillas Holandesas');
INSERT INTO paises (iso, nombre) VALUES('SA', 'Arabia Saudí');
INSERT INTO paises (iso, nombre) VALUES('DZ', 'Argelia');
INSERT INTO paises (iso, nombre) VALUES('AR', 'Argentina');
INSERT INTO paises (iso, nombre) VALUES('AM', 'Armenia');
INSERT INTO paises (iso, nombre) VALUES('AW', 'Aruba');
INSERT INTO paises (iso, nombre) VALUES('AU', 'Australia');
INSERT INTO paises (iso, nombre) VALUES('AT', 'Austria');
INSERT INTO paises (iso, nombre) VALUES('AZ', 'Azerbaiyán');
INSERT INTO paises (iso, nombre) VALUES('BS', 'Bahamas');
INSERT INTO paises (iso, nombre) VALUES('BH', 'Bahréin');
INSERT INTO paises (iso, nombre) VALUES('BD', 'Bangladesh');
INSERT INTO paises (iso, nombre) VALUES('BB', 'Barbados');
INSERT INTO paises (iso, nombre) VALUES('BY', 'Bielorrusia');
INSERT INTO paises (iso, nombre) VALUES('BE', 'Bélgica');
INSERT INTO paises (iso, nombre) VALUES('BZ', 'Belice');
INSERT INTO paises (iso, nombre) VALUES('BJ', 'Benin');
INSERT INTO paises (iso, nombre) VALUES('BM', 'Bermudas');
INSERT INTO paises (iso, nombre) VALUES('BT', 'Bhután');
INSERT INTO paises (iso, nombre) VALUES('BO', 'Bolivia');
INSERT INTO paises (iso, nombre) VALUES('BA', 'Bosnia y Herzegovina');
INSERT INTO paises (iso, nombre) VALUES('BW', 'Botsuana');
INSERT INTO paises (iso, nombre) VALUES('BV', 'Isla Bouvet');
INSERT INTO paises (iso, nombre) VALUES('BR', 'Brasil');
INSERT INTO paises (iso, nombre) VALUES('BN', 'Brunéi');
INSERT INTO paises (iso, nombre) VALUES('BG', 'Bulgaria');
INSERT INTO paises (iso, nombre) VALUES('BF', 'Burkina Faso');
INSERT INTO paises (iso, nombre) VALUES('BI', 'Burundi');
INSERT INTO paises (iso, nombre) VALUES('CV', 'Cabo Verde');
INSERT INTO paises (iso, nombre) VALUES('KY', 'Islas Caimán');
INSERT INTO paises (iso, nombre) VALUES('KH', 'Camboya');
INSERT INTO paises (iso, nombre) VALUES('CM', 'Camerún');
INSERT INTO paises (iso, nombre) VALUES('CA', 'Canadá');
INSERT INTO paises (iso, nombre) VALUES('CF', 'República Centroafricana');
INSERT INTO paises (iso, nombre) VALUES('TD', 'Chad');
INSERT INTO paises (iso, nombre) VALUES('CZ', 'República Checa');
INSERT INTO paises (iso, nombre) VALUES('CL', 'Chile');
INSERT INTO paises (iso, nombre) VALUES('CN', 'China');
INSERT INTO paises (iso, nombre) VALUES('CY', 'Chipre');
INSERT INTO paises (iso, nombre) VALUES('CX', 'Isla de Navidad');
INSERT INTO paises (iso, nombre) VALUES('VA', 'Ciudad del Vaticano');
INSERT INTO paises (iso, nombre) VALUES('CC', 'Islas Cocos');
INSERT INTO paises (iso, nombre) VALUES('CO', 'Colombia');
INSERT INTO paises (iso, nombre) VALUES('KM', 'Comoras');
INSERT INTO paises (iso, nombre) VALUES('CD', 'República Democrática del Congo');
INSERT INTO paises (iso, nombre) VALUES('CG', 'Congo');
INSERT INTO paises (iso, nombre) VALUES('CK', 'Islas Cook');
INSERT INTO paises (iso, nombre) VALUES('KP', 'Corea del Norte');
INSERT INTO paises (iso, nombre) VALUES('KR', 'Corea del Sur');
INSERT INTO paises (iso, nombre) VALUES('CI', 'Costa de Marfil');
INSERT INTO paises (iso, nombre) VALUES('CR', 'Costa Rica');
INSERT INTO paises (iso, nombre) VALUES('HR', 'Croacia');
INSERT INTO paises (iso, nombre) VALUES('CU', 'Cuba');
INSERT INTO paises (iso, nombre) VALUES('DK', 'Dinamarca');
INSERT INTO paises (iso, nombre) VALUES('DM', 'Dominica');
INSERT INTO paises (iso, nombre) VALUES('DO', 'República Dominicana');
INSERT INTO paises (iso, nombre) VALUES('EC', 'Ecuador');
INSERT INTO paises (iso, nombre) VALUES('EG', 'Egipto');
INSERT INTO paises (iso, nombre) VALUES('SV', 'El Salvador');
INSERT INTO paises (iso, nombre) VALUES('AE', 'Emiratos Árabes Unidos');
INSERT INTO paises (iso, nombre) VALUES('ER', 'Eritrea');
INSERT INTO paises (iso, nombre) VALUES('SK', 'Eslovaquia');
INSERT INTO paises (iso, nombre) VALUES('SI', 'Eslovenia');
INSERT INTO paises (iso, nombre) VALUES('ES', 'España');
INSERT INTO paises (iso, nombre) VALUES('UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO paises (iso, nombre) VALUES('US', 'Estados Unidos');
INSERT INTO paises (iso, nombre) VALUES('EE', 'Estonia');
INSERT INTO paises (iso, nombre) VALUES('ET', 'Etiopía');
INSERT INTO paises (iso, nombre) VALUES('FO', 'Islas Feroe');
INSERT INTO paises (iso, nombre) VALUES('PH', 'Filipinas');
INSERT INTO paises (iso, nombre) VALUES('FI', 'Finlandia');
INSERT INTO paises (iso, nombre) VALUES('FJ', 'Fiyi');
INSERT INTO paises (iso, nombre) VALUES('FR', 'Francia');
INSERT INTO paises (iso, nombre) VALUES('GA', 'Gabón');
INSERT INTO paises (iso, nombre) VALUES('GM', 'Gambia');
INSERT INTO paises (iso, nombre) VALUES('GE', 'Georgia');
INSERT INTO paises (iso, nombre) VALUES('GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO paises (iso, nombre) VALUES('GH', 'Ghana');
INSERT INTO paises (iso, nombre) VALUES('GI', 'Gibraltar');
INSERT INTO paises (iso, nombre) VALUES('GD', 'Granada');
INSERT INTO paises (iso, nombre) VALUES('GR', 'Grecia');
INSERT INTO paises (iso, nombre) VALUES('GL', 'Groenlandia');
INSERT INTO paises (iso, nombre) VALUES('GP', 'Guadalupe');
INSERT INTO paises (iso, nombre) VALUES('GU', 'Guam');
INSERT INTO paises (iso, nombre) VALUES('GT', 'Guatemala');
INSERT INTO paises (iso, nombre) VALUES('GF', 'Guayana Francesa');
INSERT INTO paises (iso, nombre) VALUES('GN', 'Guinea');
INSERT INTO paises (iso, nombre) VALUES('GQ', 'Guinea Ecuatorial');
INSERT INTO paises (iso, nombre) VALUES('GW', 'Guinea-Bissau');
INSERT INTO paises (iso, nombre) VALUES('GY', 'Guyana');
INSERT INTO paises (iso, nombre) VALUES('HT', 'Haití');
INSERT INTO paises (iso, nombre) VALUES('HM', 'Islas Heard y McDonald');
INSERT INTO paises (iso, nombre) VALUES('HN', 'Honduras');
INSERT INTO paises (iso, nombre) VALUES('HK', 'Hong Kong');
INSERT INTO paises (iso, nombre) VALUES('HU', 'Hungría');
INSERT INTO paises (iso, nombre) VALUES('IN', 'India');
INSERT INTO paises (iso, nombre) VALUES('ID', 'Indonesia');
INSERT INTO paises (iso, nombre) VALUES('IR', 'Irán');
INSERT INTO paises (iso, nombre) VALUES('IQ', 'Iraq');
INSERT INTO paises (iso, nombre) VALUES('IE', 'Irlanda');
INSERT INTO paises (iso, nombre) VALUES('IS', 'Islandia');
INSERT INTO paises (iso, nombre) VALUES('IL', 'Israel');
INSERT INTO paises (iso, nombre) VALUES('IT', 'Italia');
INSERT INTO paises (iso, nombre) VALUES('JM', 'Jamaica');
INSERT INTO paises (iso, nombre) VALUES('JP', 'Japón');
INSERT INTO paises (iso, nombre) VALUES('JO', 'Jordania');
INSERT INTO paises (iso, nombre) VALUES('KZ', 'Kazajstán');
INSERT INTO paises (iso, nombre) VALUES('KE', 'Kenia');
INSERT INTO paises (iso, nombre) VALUES('KG', 'Kirguistán');
INSERT INTO paises (iso, nombre) VALUES('KI', 'Kiribati');
INSERT INTO paises (iso, nombre) VALUES('KW', 'Kuwait');
INSERT INTO paises (iso, nombre) VALUES('LA', 'Laos');
INSERT INTO paises (iso, nombre) VALUES('LS', 'Lesotho');
INSERT INTO paises (iso, nombre) VALUES('LV', 'Letonia');
INSERT INTO paises (iso, nombre) VALUES('LB', 'Líbano');
INSERT INTO paises (iso, nombre) VALUES('LR', 'Liberia');
INSERT INTO paises (iso, nombre) VALUES('LY', 'Libia');
INSERT INTO paises (iso, nombre) VALUES('LI', 'Liechtenstein');
INSERT INTO paises (iso, nombre) VALUES('LT', 'Lituania');
INSERT INTO paises (iso, nombre) VALUES('LU', 'Luxemburgo');
INSERT INTO paises (iso, nombre) VALUES('MO', 'Macao');
INSERT INTO paises (iso, nombre) VALUES('MK', 'ARY Macedonia');
INSERT INTO paises (iso, nombre) VALUES('MG', 'Madagascar');
INSERT INTO paises (iso, nombre) VALUES('MY', 'Malasia');
INSERT INTO paises (iso, nombre) VALUES('MW', 'Malawi');
INSERT INTO paises (iso, nombre) VALUES('MV', 'Maldivas');
INSERT INTO paises (iso, nombre) VALUES('ML', 'Malí');
INSERT INTO paises (iso, nombre) VALUES('MT', 'Malta');
INSERT INTO paises (iso, nombre) VALUES('FK', 'Islas Malvinas');
INSERT INTO paises (iso, nombre) VALUES('MP', 'Islas Marianas del Norte');
INSERT INTO paises (iso, nombre) VALUES('MA', 'Marruecos');
INSERT INTO paises (iso, nombre) VALUES('MH', 'Islas Marshall');
INSERT INTO paises (iso, nombre) VALUES('MQ', 'Martinica');
INSERT INTO paises (iso, nombre) VALUES('MU', 'Mauricio');
INSERT INTO paises (iso, nombre) VALUES('MR', 'Mauritania');
INSERT INTO paises (iso, nombre) VALUES('YT', 'Mayotte');
INSERT INTO paises (iso, nombre) VALUES('MX', 'México');
INSERT INTO paises (iso, nombre) VALUES('FM', 'Micronesia');
INSERT INTO paises (iso, nombre) VALUES('MD', 'Moldavia');
INSERT INTO paises (iso, nombre) VALUES('MC', 'Mónaco');
INSERT INTO paises (iso, nombre) VALUES('MN', 'Mongolia');
INSERT INTO paises (iso, nombre) VALUES('MS', 'Montserrat');
INSERT INTO paises (iso, nombre) VALUES('MZ', 'Mozambique');
INSERT INTO paises (iso, nombre) VALUES('MM', 'Myanmar');
INSERT INTO paises (iso, nombre) VALUES('NA', 'Namibia');
INSERT INTO paises (iso, nombre) VALUES('NR', 'Nauru');
INSERT INTO paises (iso, nombre) VALUES('NP', 'Nepal');
INSERT INTO paises (iso, nombre) VALUES('NI', 'Nicaragua');
INSERT INTO paises (iso, nombre) VALUES('NE', 'Níger');
INSERT INTO paises (iso, nombre) VALUES('NG', 'Nigeria');
INSERT INTO paises (iso, nombre) VALUES('NU', 'Niue');
INSERT INTO paises (iso, nombre) VALUES('NF', 'Isla Norfolk');
INSERT INTO paises (iso, nombre) VALUES('NO', 'Noruega');
INSERT INTO paises (iso, nombre) VALUES('NC', 'Nueva Caledonia');
INSERT INTO paises (iso, nombre) VALUES('NZ', 'Nueva Zelanda');
INSERT INTO paises (iso, nombre) VALUES('OM', 'Omán');
INSERT INTO paises (iso, nombre) VALUES('NL', 'Países Bajos');
INSERT INTO paises (iso, nombre) VALUES('PK', 'Pakistán');
INSERT INTO paises (iso, nombre) VALUES('PW', 'Palau');
INSERT INTO paises (iso, nombre) VALUES('PS', 'Palestina');
INSERT INTO paises (iso, nombre) VALUES('PA', 'Panamá');
INSERT INTO paises (iso, nombre) VALUES('PG', 'Papúa Nueva Guinea');
INSERT INTO paises (iso, nombre) VALUES('PY', 'Paraguay');
INSERT INTO paises (iso, nombre) VALUES('PE', 'Perú');
INSERT INTO paises (iso, nombre) VALUES('PN', 'Islas Pitcairn');
INSERT INTO paises (iso, nombre) VALUES('PF', 'Polinesia Francesa');
INSERT INTO paises (iso, nombre) VALUES('PL', 'Polonia');
INSERT INTO paises (iso, nombre) VALUES('PT', 'Portugal');
INSERT INTO paises (iso, nombre) VALUES('PR', 'Puerto Rico');
INSERT INTO paises (iso, nombre) VALUES('QA', 'Qatar');
INSERT INTO paises (iso, nombre) VALUES('GB', 'Reino Unido');
INSERT INTO paises (iso, nombre) VALUES('RE', 'Reunión');
INSERT INTO paises (iso, nombre) VALUES('RW', 'Ruanda');
INSERT INTO paises (iso, nombre) VALUES('RO', 'Rumania');
INSERT INTO paises (iso, nombre) VALUES('RU', 'Rusia');
INSERT INTO paises (iso, nombre) VALUES('EH', 'Sahara Occidental');
INSERT INTO paises (iso, nombre) VALUES('SB', 'Islas Salomón');
INSERT INTO paises (iso, nombre) VALUES('WS', 'Samoa');
INSERT INTO paises (iso, nombre) VALUES('AS', 'Samoa Americana');
INSERT INTO paises (iso, nombre) VALUES('KN', 'San Cristóbal y Nevis');
INSERT INTO paises (iso, nombre) VALUES('SM', 'San Marino');
INSERT INTO paises (iso, nombre) VALUES('PM', 'San Pedro y Miquelón');
INSERT INTO paises (iso, nombre) VALUES('VC', 'San Vicente y las Granadinas');
INSERT INTO paises (iso, nombre) VALUES('SH', 'Santa Helena');
INSERT INTO paises (iso, nombre) VALUES('LC', 'Santa Lucía');
INSERT INTO paises (iso, nombre) VALUES('ST', 'Santo Tomé y Príncipe');
INSERT INTO paises (iso, nombre) VALUES('SN', 'Senegal');
INSERT INTO paises (iso, nombre) VALUES('CS', 'Serbia y Montenegro');
INSERT INTO paises (iso, nombre) VALUES('SC', 'Seychelles');
INSERT INTO paises (iso, nombre) VALUES('SL', 'Sierra Leona');
INSERT INTO paises (iso, nombre) VALUES('SG', 'Singapur');
INSERT INTO paises (iso, nombre) VALUES('SY', 'Siria');
INSERT INTO paises (iso, nombre) VALUES('SO', 'Somalia');
INSERT INTO paises (iso, nombre) VALUES('LK', 'Sri Lanka');
INSERT INTO paises (iso, nombre) VALUES('SZ', 'Suazilandia');
INSERT INTO paises (iso, nombre) VALUES('ZA', 'Sudáfrica');
INSERT INTO paises (iso, nombre) VALUES('SD', 'Sudán');
INSERT INTO paises (iso, nombre) VALUES('SE', 'Suecia');
INSERT INTO paises (iso, nombre) VALUES('CH', 'Suiza');
INSERT INTO paises (iso, nombre) VALUES('SR', 'Surinam');
INSERT INTO paises (iso, nombre) VALUES('SJ', 'Svalbard y Jan Mayen');
INSERT INTO paises (iso, nombre) VALUES('TH', 'Tailandia');
INSERT INTO paises (iso, nombre) VALUES('TW', 'Taiwán');
INSERT INTO paises (iso, nombre) VALUES('TZ', 'Tanzania');
INSERT INTO paises (iso, nombre) VALUES('TJ', 'Tayikistán');
INSERT INTO paises (iso, nombre) VALUES('IO', 'Territorio Británico del Océano Índico');
INSERT INTO paises (iso, nombre) VALUES('TF', 'Territorios Australes Franceses');
INSERT INTO paises (iso, nombre) VALUES('TL', 'Timor Oriental');
INSERT INTO paises (iso, nombre) VALUES('TG', 'Togo');
INSERT INTO paises (iso, nombre) VALUES('TK', 'Tokelau');
INSERT INTO paises (iso, nombre) VALUES('TO', 'Tonga');
INSERT INTO paises (iso, nombre) VALUES('TT', 'Trinidad y Tobago');
INSERT INTO paises (iso, nombre) VALUES('TN', 'Túnez');
INSERT INTO paises (iso, nombre) VALUES('TC', 'Islas Turcas y Caicos');
INSERT INTO paises (iso, nombre) VALUES('TM', 'Turkmenistán');
INSERT INTO paises (iso, nombre) VALUES('TR', 'Turquía');
INSERT INTO paises (iso, nombre) VALUES('TV', 'Tuvalu');
INSERT INTO paises (iso, nombre) VALUES('UA', 'Ucrania');
INSERT INTO paises (iso, nombre) VALUES('UG', 'Uganda');
INSERT INTO paises (iso, nombre) VALUES('UY', 'Uruguay');
INSERT INTO paises (iso, nombre) VALUES('UZ', 'Uzbekistán');
INSERT INTO paises (iso, nombre) VALUES('VU', 'Vanuatu');
INSERT INTO paises (iso, nombre) VALUES('VE', 'Venezuela');
INSERT INTO paises (iso, nombre) VALUES('VN', 'Vietnam');
INSERT INTO paises (iso, nombre) VALUES('VG', 'Islas Vírgenes Británicas');
INSERT INTO paises (iso, nombre) VALUES('VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO paises (iso, nombre) VALUES('WF', 'Wallis y Futuna');
INSERT INTO paises (iso, nombre) VALUES('YE', 'Yemen');
INSERT INTO paises (iso, nombre) VALUES('DJ', 'Yibuti');
INSERT INTO paises (iso, nombre) VALUES('ZM', 'Zambia');
INSERT INTO paises (iso, nombre) VALUES('ZW', 'Zimbabue');